#!/bin/bash

envsubst <<EOF
FQDN is $FQDN
EOF

CONFDIR=/var/www/html/poprox/app/configs/$FQDN
mkdir -p $CONFDIR

envsubst > $CONFDIR/dbconn-memex_ht.ini <<EOF
[dbopts]
table_prefix = ""
dns_scheme = "ini"
dns_value = ""

[dbconn]
driver = "mysql"
host = "$MEMEXDBHOST"
;port = 3306
dbname = "memex_ht"
username = "$MEMEXDBUSER"
password = "$MEMEXDBPASS"
EOF

envsubst > $CONFDIR/dbconn-memex_ist.ini <<EOF
[dbopts]
table_prefix = ""
dns_scheme = "ini"
dns_value = ""

[dbconn]
driver = "mysql"
host = "$ISTDBHOST"
;port = 3306
dbname = "memex_ist"
username = "$ISTDBUSER"
password = "$ISTDBPASS"
EOF

envsubst > $CONFDIR/dbconn-webapp.ini <<EOF
[dbopts]
table_prefix = "webapp_"
dns_scheme = "ini"
dns_value = ""

[dbconn]
driver = "mysql"
host = "$WEBAPPDBHOST"
;port = 3306
dbname = "memex_ist_webapp"
username = "$WEBAPPDBUSER"
password = "$WEBAPPDBPASS"
EOF

envsubst > $CONFDIR/I18N.php <<EOF
<?php
/*
 * Copyright (C) 2012 Blackmoon Info Tech Services
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace BitsTheater\\configs;
use BitsTheater\\res\\ResI18N as BaseI18N;
{//begin namespace

final class I18N extends BaseI18N {
	const DEFAULT_LANG = 'en';
	const DEFAULT_REGION = 'US';
}//end class

}//end namespace
EOF

envsubst > $CONFDIR/Settings.php <<EOF
<?php
/*
 * Copyright (C) 2012 Blackmoon Info Tech Services
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace BitsTheater\\configs;
{//begin namespace
define('_DEBUG_APP',true);

class Settings extends \\stdClass {

	const APP_ID = '64E5C9AE-E38A-EE61-DAA3-C4C42FF97C27';

	const PAGE_Landing = 'home';
	
	static function getAppId() {
		return self::APP_ID;
	}
	
	static function getLandingPage() {
		return self::PAGE_Landing;
	}
	
}//end class

}//end namespace
EOF

apache2 -DFOREGROUND
